### ISSUE TITLE
Occlusion errors in the second demo scene

### ISSUE THREAD

**Issue by JensRestemeier** [dhaumont/visilib#6]
Platform:
Win10, Visual Studio 2022, x64 build (debug and release), without exact arithmetic libraries

To reproduce:
Launch visilibDemo.exe, press X to skip to the second demo: Two triangles and a large mesh.
The initial view is correct. Press "Space" to enable animation. I'm observing three cases:
- correct case where stablines only pass through the empty space
- inverse case where stablines pass only though the occluding polygon
- stablines pass through both the empty space and the occluding polygon

Is that a bug, or a side-effect of non-exact arithmetic?

**Comment by dhaumont** [comment]
Thanks for reporting these issues.
The first goal was to perform binary occlusion request (ie answer the binary question "are two polygons mutually visible"). In this context, Visilib is used as an aperture finder, guiding a ray casting process until mutual visibility is determined when a free ray is found. 
It has been extended to pursue the computation until all occluders have been processed, allowing to perform the complete visibility calculation. In that context, Visilib construct the equivalent of the Visibility Skeleton, allowing to find all the visibility events between the two polygons. 
Unfortunately, this more involved computation is not as robust as the more simple occlusion query, leading to some bugs like the one you described.
Some of these bugs have been solved in the WIP branch, but still needs to be merged in the main branch.
Exact aritmetic sometimes can also help, but the implementation is not perfect and some inconsistencies subsist even when you use it.

**Comment by JensRestemeier** [comment]
Does this mean it may terminate before doing the csg step if a ray trace succeeds? I want to specifically test the CSG operation, is it possible to disable the ray test until all CSG operations are applied?

**Comment by JensRestemeier** [comment]
The problem seems to be precision related. I added support for mpfr and lowered the tolerance, and the errors seem to disappear.
